# Generated by Django 5.2.8 on 2026-01-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_email_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
