# Generated by Django 5.2.8 on 2026-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_temporaryuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_block",
            field=models.BooleanField(default=False),
        ),
    ]
