# Generated by Django 5.2.8 on 2026-01-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_is_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaryuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="temporaryuser",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="temporaryuser",
            name="username",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
