# Generated by Django 5.2.8 on 2026-01-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_temporaryuser_email_temporaryuser_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporaryuser",
            name="user",
        ),
    ]
