# Generated by Django 5.2.8 on 2026-01-04 10:07

import django.db.models.deletion
from django.db import migrations, models

import mailing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="Тема письма"),
                ),
                (
                    "body",
                    models.TextField(blank=True, null=True, verbose_name="Тело письма"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата и время последнего обновления"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="Почта"),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="Ф.И.О.")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=mailing.models.Campaign.get_default_start_time,
                        verbose_name="Дата и время начала отправки",
                    ),
                ),
                (
                    "first_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        default=mailing.models.Campaign.get_default_end_time,
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создана", "Создана"),
                            ("Запущена", "Запущена"),
                            ("Завершена", "Завершена"),
                        ],
                        default="Создана",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaignes",
                        to="mailing.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "subscribers",
                    models.ManyToManyField(
                        related_name="campaigns",
                        to="mailing.subscriber",
                        verbose_name="Получатели",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="subscribers",
            field=models.ManyToManyField(related_name="messages", to="mailing.subscriber"),
        ),
        migrations.CreateModel(
            name="EmailAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("successful", "Успешно"), ("failed", "Не успешно")],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.campaign",
                        verbose_name="Рассылка",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="mailing.subscriber",
                    ),
                ),
            ],
        ),
    ]
