# Generated by Django 5.2.8 on 2026-01-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="end_time",
            field=models.DateTimeField(verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_time",
            field=models.DateTimeField(verbose_name="Дата и время начала отправки"),
        ),
    ]
