# Generated by Django 5.2.8 on 2026-01-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_campaign_end_time_alter_campaign_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="subscribers",
        ),
    ]
