# Generated by Django 5.2.8 on 2025-12-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_campaign_emailattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="end_time",
            field=models.DateTimeField(
                null=True, verbose_name="Дата и время окончания отправки"
            ),
        ),
    ]
